services:
  eureka:
    image: cassiocintra/eureka
    restart: always
    build: ./eureka-server
    working_dir: /eureka-server
    ports:
      - "8761:8761"
    environment:
      TZ: America/Sao_Paulo
    command:
      - mvn spring-boot:run
    networks:
      - microservice-network

  ms-clients:
    image: cassiocintra/ms-clients
    restart: always
    build: ./ms-clients
    working_dir: /ms-clients
    environment:
      TZ: America/Sao_Paulo
    command:
      - mvn spring-boot:run
    depends_on:
      - eureka
    networks:
      - microservice-network

  hello-world:
    image: cassiocintra/hello-world
    restart: always
    build: ./hello-world
    working_dir: /hello-world
    environment:
      TZ: America/Sao_Paulo
    command:
      - mvn spring-boot:run
    depends_on:
      - eureka
    networks:
      - microservice-network

  gateway:
    image: cassiocintra/gateway
    restart: always
    build: ./ms-gateway
    working_dir: /ms-gateway
    ports:
      - "8080:8080"
    environment:
      TZ: America/Sao_Paulo
    command:
      - mvn spring-boot:run
    depends_on:
      - eureka
    networks:
      - microservice-network
networks:
  microservice-network:
    driver: bridge
